# Generated by Django 3.2 on 2022-07-05 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF : Somente números')),
                ('tipo_usuario', models.CharField(choices=[('O', 'Operador'), ('C', 'Cliente')], max_length=1)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.IntegerField(verbose_name='Duração por atendimento')),
                ('qtVagas', models.IntegerField(verbose_name='Quantidade de vagas por dia')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_agendou', to='agendamentos.usuario')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador_criou', to='agendamentos.usuario')),
            ],
        ),
    ]
