# Generated by Django 3.2 on 2022-07-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_horario_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='cod',
            field=models.IntegerField(null=True),
        ),
    ]
