# Generated by Django 3.2 on 2022-07-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_horario_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='cod',
        ),
    ]
