# Generated by Django 3.2 on 2023-05-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_auto_20220720_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='cliente',
            field=models.ManyToManyField(blank=True, default=None, related_name='horarios', to='agendamentos.Usuario'),
        ),
    ]
